version: "3.8"

services:
  database_solid:
    image: postgres
    container_name: database_solid
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=solid
    volumes:
      - pgdata:/data/postgres
    networks:
      - api
  app:
    build: .
    container_name: ignite_solid
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/src/app
    depends_on:
      - database_solid
    networks:
      - api


volumes:
  pgdata:
    driver: local

networks:
  api: